### PR TITLE
Dashboard: Remove calls to `TableColumns` API

### PR DESCRIPTION
**Pull request by ericpgreen2**
Addresses the second bullet here: https://github.com/rilldata/rill/issues/3803

### CODE REVIEW

**Review by djbarnwal — CHANGES_REQUESTED** [review]
Getting these warnings in the console - 

image

Extra props are being passed to `NoTimeDimensionCTA`.

Also saw a reference of  `createQueryServiceTableColumns` being used in `RowViewer` component used in the dashboard. It's behind a feature flag in the same manner as this component. Do we have to change that as well?

**Comment by ericpgreen2** [comment]
> Extra props are being passed to `NoTimeDimensionCTA`.

Ah, thanks for catching that. Just fixed.
 
> Also saw a reference of `createQueryServiceTableColumns` being used in `RowViewer` component used in the dashboard. It's behind a feature flag in the same manner as this component. Do we have to change that as well?

We'd really only need to fix it once we promote the feature to the Cloud UI, but I just fixed it now anyways so we don't forget.

**Review by djbarnwal — CHANGES_REQUESTED** [review]
Seeing some issues with the Rows table.

1. Opening the table throws a 429 error. 
2. Selecting a leaderboard value after opening the table crashes the app

image

**Review by djbarnwal — APPROVED** [review]
Tested locally, works as expected! 
Approving so that you can merge after resolving the merge conflicts.

**Pull request merged**
