### PR TITLE
Feat: Add auto-save toggle to model workspace

### LINKED ISSUE #4301: Manual Trigger for saving models
Refer to more details here - https://www.notion.so/rilldata/Make-Rill-dev-usable-at-scale-21ef9fb859874a86aa8d5e4cb808f830

### PR DESCRIPTION
**Pull request by briangregoryholmes**
This PR adds a manual trigger for saving models and persists this preference in local storage via the WorkspaceLayout store.

Closes #4301

### CODE REVIEW

**Comment by briangregoryholmes** [comment]
@nishantmonu51 @AdityaHegde In the PRD, there's seems to be a differentiation between "Save" and "Profile". I believe we talked about this last week, but can you clarify what that means? Currently, updating the model invalidates the `modelQuery`. When this gets invalidated, the `tableQuery` will refetch. Is the PRD saying that we should disentangle these two queries? "Save" would run the `updateModel` mutation, but the `tableQuery` won't be refetched until you click Profile?

**Review by AdityaHegde — APPROVED** [review]

**Comment by nishantmonu51** [comment]
@briangregoryholmes : Yes that was the initial intent, that the profile only works when a user explicitly wants to do that. Doing it as part of save is also fine with dev partition change.

**Review by nishantmonu51 — APPROVED** [review]
Just did a quick experience pass, LGTM

**Comment by nishantmonu51** [comment]
@briangregoryholmes : Found 1 issue during experience pass - 
Make changes to model, navigate to other model, choose yes, leave model, It doesn't work

**Pull request merged**
