### PR TITLE
fix: layout of connector items in Safari

### PR DESCRIPTION
**Pull request by briangregoryholmes**
In Safari:

Screenshot 2024-10-15 at 10 14 02 AM

After (Chrome & Safari):
Screenshot 2024-10-15 at 5 53 53 PM

### CODE REVIEW

**Review by ericpgreen2 — CHANGES_REQUESTED** [review]
I'm seeing missing icons in Chrome:
image

And icons are vertically mis-aligned in Safari:
image

**Comment by ericpgreen2** [comment]
Hmm, are you sure that's what you see in Safari? I've emptied my Safari cache & I'm still seeing this:
image

**Comment by briangregoryholmes** [comment]
I'm on 17.6. I made a small change and tested on 16.5 on BrowserStack, but I didn't have trial minutes left for older versions.

**Comment by ericpgreen2** [comment]
Oh, I'm on 15.6.1. It looks great now

**Review by ericpgreen2 — APPROVED** [review]

**Pull request merged**
