### PR TITLE
convert select component, consolidate bookmark dialog

### PR DESCRIPTION
**Pull request by briangregoryholmes**

### CODE REVIEW

**Comment by ericpgreen2** [comment]
@briangregoryholmes is this ready for review? Mind just fixing the code quality test?

**Review by ericpgreen2 — APPROVED** [review]
Looks way better aesthetically.

UXQA – I tried the Create Bookmark form, and making a selection in the new Select component caused the dialog to close. [See JAM](https://jam.dev/c/48a573be-4269-410a-8987-0abd0516c7fd)

**Comment by briangregoryholmes** [comment]
For the sake of practicality, I've solved this by consolidating the CreateBookmarkDialog and EditBookmarkDialog components into a single component that uses the ShadCN dialog. The other dialog was closing because it was naively detecting an outside click. There is a lot that has to be done to make our dialog implementations more consistent throughout the application. The changes in this PR are small just to get it over the line.

**Review by ericpgreen2 — CHANGES_REQUESTED** [review]
I like the cleanup. Two UXQA findings:
1. The Bookmark dialog's absolute time range toggle doesn't seem to be respected. It always flips to "on". [See Jam](https://jam.dev/c/19361cd0-464e-459f-a1db-3097fc9ae77c)
2. The `TimePicker` component isn't seeming to create valid times. When I create a scheduled report, the chosen time isn't respected, and the "edit" form is not able to populate the time field correctly. [See Jam](https://jam.dev/c/9165ad41-4f8b-41b7-ad40-04555e0c95a1).

**Comment by ericpgreen2** [comment]
It still seems like the Bookmark toggles aren't being respected: [Jam](https://jam.dev/c/71d3e89c-fd8b-4171-a399-0f1d90fbb656)

**Comment by briangregoryholmes** [comment]
Could not reproduce any issue with the filters only toggle, but the other one should be resolved.

**Pull request merged**
