### PR TITLE
fix #3910

### LINKED ISSUE #3910: Adjust gradient applied to the time series
Initial application of brand color to time series shapes may need to be tuned down in opacity as sometimes it obscures the gray comparison line:
Screenshot 2024-01-25 at 2 58 42 PM

Please see my proposed gradient in Figma, which is 30% opacity top to bottom:
https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=8550-763794&mode=design&t=BkgjZVfS7TyqoZIL-11

### PR DESCRIPTION
**Pull request by bcolloran**
fixes #3910 -- opacity in chart updated to match https://www.figma.com/file/Qt6EyotCBS3V6O31jVhMQ7/RILL?type=design&node-id=8550%3A763794&mode=design&t=sQngibmwoM8Y5zZV-1

image

### CODE REVIEW

**Comment by ericpgreen2** [comment]
It looks like the gradient was removed – it's now just a solid color.

Here's what I'm seeing in TDD:
image

**Comment by bcolloran** [comment]
duh yes it is. even in my screenshot I took. sorry, I don't know how I missed that. I guess I was just so focused on the opacity that I didn't notice the gradient 👎 :-(  fix coming, one sec

**Comment by bcolloran** [comment]
Ok, it's fixed. Sorry I missed this earlier @ericpgreen2 


here's what it looks like with the gradient restored:

image

image


and themed:

image

image

**Review by ericpgreen2 — APPROVED** [review]
Looks good!

**Pull request merged**
