### PR TITLE
use brand colors for bignum and leaderboard names

### PR DESCRIPTION
**Pull request by bcolloran**
partial fix of #3907, teeny tweak to colors in a couple places

image

### CODE REVIEW

**Review by jkhwu — APPROVED** [review]
Looks good @bcolloran !

**Review by ericpgreen2 — APPROVED** [review]

**Comment by ericpgreen2** [comment]
I've noticed that the same header color should be applied to the dimension detail table as well.

**Comment by jkhwu** [comment]
@ericpgreen2 I actually chose to change these colors to make them look like links and encourage users to mouse over and click to drill down (so far no first-time users we've observed have discovered Dimension Detail view on their own). So by that logic we may not need to apply the same header color to dimension detail view, since there's not another surface that would be revealed if we click that.

**Comment by bcolloran** [comment]
@jkhwu, when you decide on which solution you prefer, would you mind capturing that decision in a new issue so they are tracked? They are likely to get lost in the shuffle as a comment in a merged PR. Thanks!

**Pull request merged**
