### PR TITLE
fix: file conflict resolution

### PR DESCRIPTION
**Pull request by briangregoryholmes**
- Updates conflict detection logic to be less intrusive
- Updates alert copy
- Adds diff/merge view
- Adds saving/error indicators to sidebar and save button

Screenshot 2024-12-17 at 4 16 52 PM
Screenshot 2024-12-17 at 10 02 23 PM

Screenshot 2024-12-17 at 3 29 55 PM

### CODE REVIEW

**Comment by nishantmonu51** [comment]
@briangregoryholmes : Is this ready for review ?

**Review by ericpgreen2 — COMMENTED** [review]
Overall, feels good!

UXQA:
1. With autosave disabled, I add text (e.g. "abc"), then delete that same text, then attempt to save the file (the "unsaved changes" indicator was showing), it fails to save. ([Jam](https://jam.dev/c/40662f4a-5900-4be6-a20a-42cda2d206f7))
2. After I accept remote changes, I see the red exclamation point.
    image

@mindspank could we call you the Product Owner of the code editor, and can you give this a look too?

**Comment by briangregoryholmes** [comment]
All fixed. I also extended the autosave debounce to 650ms, which feels better to me.

**Comment by ericpgreen2** [comment]
The "Accept current" button is unresponsive for me: [Jam](https://jam.dev/c/6cc7ed99-dcd1-4701-9cc6-8cd96a0cddeb)

**Review by ericpgreen2 — APPROVED** [review]
Approving so you can merge at your discretion

**Pull request merged**
