### PR TITLE
refactor: apply cors

### PR DESCRIPTION
**Pull request by Kavinjsir**
### Description

1. Replace `cors allowed-origins` with default localHttpUrl
2. Add a flag `--allowed-origins` to input additional `allowed-origins`

### Motivation

Resolve https://github.com/rilldata/rill/issues/5039

### CODE REVIEW

**Comment by Kavinjsir** [comment]
I think this PR is ready for review.
One concern left is `CSP`.
It looks the current one has well defined:
https://github.com/rilldata/rill/blob/v0.47.5/netlify.toml#L6-L14

Perhaps the only concern is ever want to drop `unsafe-eval` or `unsafe-inline`.
cc: @himadrisingh would you have some suggestions?

**Comment by Kavinjsir** [comment]
> > We have third party dependencies which require unsafe-eval, unless we get them compliant with cso it would be difficult.
> 
> @himadrisingh if vega is the mentioned one, it seems they have a resolution, I tried opening a PR for discussion at: ~#4784~ #5376

As @djbarnwal has already made great contribution and there has been an upstream PR for vega to review, I think we can deal with CSP later.

**Comment by himadrisingh** [comment]
Did we test it locally and see if it fixes the issue.

**Review by himadrisingh — APPROVED** [review]

**Comment by Kavinjsir** [comment]
> Did we test it locally and see if it fixes the issue.

@himadrisingh Yeah, here’s what I tested locally:

1. **HOST A**:  ran the compiled `rill` CLI based on this PR with the following command:

```shell
go run ./cli start --verbose --debug <local-rill-project-path> --allowed-origins="http://localhost:3000" --allowed-origins="http://localhost:4000"
```

This sets the allowed origins to `["localhost:3000", "localhost:4000"]`.

2. **HOST B**: set up a simple HTTP server using:

```shell
python3 -m http.server 4003
```

With an HTML file like this:

```html
<!DOCTYPE html>
<html>

<head>
  <title>
    CORS Test
  </title>
</head>

<body>
  <script>
    fetch("http://<HOST-A-IP>:9009/v1/instances/default?sensitive=true")
      .then(res => res.json())
      .then(data => console.log(data))
      .catch(err => console.error("Error: ", err));
  </script>
</body>

</html>
```

When the port of **HOST B** is set to `3000` or `4000`, the script inside the HTML file successfully fetches results from the endpoint. For any other port value, it fails as expected.

**Pull request merged**
