### PR TITLE
feat: add pivot for timeseries

### PR DESCRIPTION
**Pull request by mindspank**
Outstanding:

* Adding divider between timeseries and leaderboards - Done
* Adjust spacing of containers for scrollbars
* The divider invites "draggability", perhaps we should add it?

### CODE REVIEW

**Comment by mindspank** [comment]
Closes #5274

**Comment by ericpgreen2** [comment]
Code looks good, though I agree that this needs some design work. The button's alignment next to the "<- All dimensions" button looks pretty rough:
image

**Review by ericpgreen2 — APPROVED** [review]
💪

**Comment by ericpgreen2** [comment]
Found a little design regression –

The back to "All dimensions" button is crowded by the rest of the buttons in the toolbar.

Before:
image

After:
image

**Pull request merged**
