### PR TITLE
UPDATE: CLI ReadME for production build and local developement #4252

### PR DESCRIPTION
**Pull request by akshayjain3450**
I have updated the command and instruction to run the start command without any errors for production or developer.

#### Issue addressed: 
#4252

#### Details:
This change is required so that developers are not facing unnecessary issue with finding the flag and not able to start rill.

## Steps to Verify
1. Follow the CLI ReadME.

### CODE REVIEW

**Comment by akshayjain3450** [comment]
@ericpgreen2 @begelundmuller Can you please review this PR?

**Comment by akshayjain3450** [comment]
> Thank you for your contribution @akshayjain3450. I have one change request – we prefer to avoid `cd` into different sub-directories in our development workflow. So can you change the PR to pass the `dev-project` as a positional argument to the executable, i.e. `./rill start dev-project`?

Understood. Will perform this change and thank you for updating my knowledge too on this.

**Comment by akshayjain3450** [comment]
@begelundmuller I have updated the PR. Please have a look. 
Thank You

**Review by begelundmuller — COMMENTED** [review]
Thank you for the changes – can you remove the addition to the comments? They are not correct, you don't need to already have a `dev-project` directory. If there isn't one, the application will show a welcome screen with different templates for initializing the project.

**Comment by akshayjain3450** [comment]
@begelundmuller made the directed changed. Thank You!

**Review by begelundmuller — APPROVED** [review]
Thanks!

**Pull request merged**
