### PR TITLE
Support infinite query when listing org users and invites

### PR DESCRIPTION
**Pull request by lovincyrus**
closes https://github.com/rilldata/rill/issues/6113

https://github.com/user-attachments/assets/95d880a2-e84b-400c-bce7-9c1d21e63916

### CODE REVIEW

**Comment by ericokuma** [comment]
Looks good!

**Review by ericpgreen2 — COMMENTED** [review]
UXQA:
1. When the users table is short, the page scrolls unnecessarily ([Jam](https://jam.dev/c/29d34c23-39b5-4988-a854-ff331b0233a8))
2. Related, when the users table is long, there are two scroll bars: one at the page-level, one at the table-level. ([Jam](https://jam.dev/c/af28bf39-764c-45bf-9564-d44a3b1b96cd))

What if we remove the table's `min-height` and just use a `max-height`, small enough so that it doesn't trigger a page-level scroll?

**Comment by ericokuma** [comment]
weird, i don't see those two issues

**Comment by lovincyrus** [comment]
> UXQA:
> 
> 1. When the users table is short, the page scrolls unnecessarily ([Jam](https://jam.dev/c/29d34c23-39b5-4988-a854-ff331b0233a8))
> 2. Related, when the users table is long, I'm seeing two scroll bars: one at the page-level, one at the table-level. ([Jam](https://jam.dev/c/af28bf39-764c-45bf-9564-d44a3b1b96cd))
> 
> What if we remove the table's `min-height` and just use a `max-height`, small enough so that it doesn't trigger a page-level scroll?

Min height is the culprit, tracing this..

**Comment by lovincyrus** [comment]
Latest demo:

https://github.com/user-attachments/assets/f89dda12-19e9-4835-bdb0-3ed1f20e555b

**Review by ericpgreen2 — APPROVED** [review]
👏

**Pull request merged**
